version: '3.7'

services:
  db:
    image: mysql
    restart: always
    container_name: 'db'
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'revenue'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app:
    build: .
    container_name: 'app'
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
